app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('admin/',views.addmin,name='addmin'),
    path('', views.home, name='home'),
    
    path('marketplace/', views.placements, name='placements'),
    path('marketplace/<placement_slug>/', views.placement_detail, name='placement-detail'),

    path('my-bids/', views.bid_summary, name='bid-summary' ),
    path('confirm-bids/', views.confirm_bids, name='confirm-bids'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
    path('emailing',views.send_email, name='emailing')


]

bidding_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

templates/about.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %}

<section class="section">
    <section class="container">

        <article class="card">
            <div class="card-content">
                <h4>About</h4>
                <p class="custom-font-1">This application was built as a side project, in order to learn how to design and build a bidding system from scratch. The theme is based on capital raising for companies. It includes an auth system, marketplace, companies, placements,
                    dashboard, mobile friendly design. I used Django mainly, to develop this application.</p>
</div>
        </article>
        <article class="card">
            <div class="card-content">
                <h4>Available Routes</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item"><span class="chip">/</span> The home page. Contains news.</li>
                    <li class="collection-item"><span class="chip">about/</span> Holds details about the application.</li>
                    <li class="collection-item"><span class="chip">register/</span> Allows users to register an account</li>
                    <li class="collection-item"><span class="chip">login/</span> Allows users to login to an account</li>
                    <li class="collection-item"><span class="chip">logout/</span> Allows users to logout and clear their session</li>

                    <li class="collection-item"><span class="chip">marketplace/</span> Listing of placements from various companies.</li>

                    <li class="collection-item"><span class="chip">marketplace/slug/</slug></span> Detailed view for a placement within the marketplace.</li>
                    <li class="collection-item"><span class="chip">my-bids/</span> User scope bid summary for available placements.</li>
                    <li class="collection-item"><span class="chip">dashboard/</span> Basic analytics and animated charts for the database.</li>

                </ul>
            </div>
        </article>


        <article class="card">
            <div class="card-content">
                <h4>Features and specs</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item">Authentication system - users can login, register and logout, passwords are securely hashed with PBKDF2 method.</li>
                    <li class="collection-item ">Certain routes are protected with a login required decorator, giving security to administrators/owners. Unregistered users are prompted to login on the home page.</li>
                    <li class="collection-item">Dashboard include dynamic and animated charts to draw insights from database.</li>
                    <li class="collection-item">Data is modelled in ORM and automatically generated by Django to RDBS of choice.</li>
                    <li class="collection-item">Data included in application is randomly generated using the <code>faker</code> library</li>
                    <li class="collection-item">App uses materialize css framework borrowing from Google's material design principles</li>
                    <li class="collection-item">App developed mainly in Django framework and Javascript.</li>
                </ul>
            </div>
        </article>

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

templates/addmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
        <a href="{% url 'app:addmin' %}" target="_blank" rel="noopener">Members</a>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <link href="https://fonts.googleapis.com/css?family=Literata|Raleway|Montserrat|Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
    <title>Bidding System</title>

    <style>
      p {
        margin-top: 0.5rem !important;
        margin-bottom: 0.5rem!important;
      }

      img {
        margin-top: 1em;
        padding: 4%;
      }

      .custom-font-1 {
        font-family: 'Literata', serif;
      } 

      h1, h2, h3, h4, h5, h6 {
        margin-top: .5em !important;
        font-family: 'Nunito', sans-serif;
        font-weight: bold;
      }

      body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      main {
        flex: 1 0 auto;
      }
        
      input:focus {
        border-bottom: 1px solid deeppink !important;
        box-shadow: 0 1px 0 0 deeppink !important;
      }


      /* ----------------------------------------------
 * Generated by Animista on 2019-7-21 13:37:41
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.fade-in {
	-webkit-animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}



    </style>
</head>
<body class="grey lighten-4">
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function(){
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    })
    </script>
</body>
</html>

templates/bid-summary.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

<section class="section">
    <section class="container">
        <div class="card">
            <div class="card-content">
                <h4>Your bid summary</h4>
                <table class="table responsive-table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Bid status</th>
                            <th>Company Name</th>
                            <th>Timestamp</th>
                            <th>$ Bidded</th>
                            <th>no. Shares</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for b in bids %}
                            <tr>
                                <td>{{ b.id }}</td>
                                <td>{% if b.confirmed %}<span class="chip">Confirmed</span>{%else%} <span class="chip indigo darken-2 white-text">Unconfirmed</span>       {%endif%}</td>
                                <td>{{ b.placement.placement_company }}</td>
                                <td>{{ b.placementbid_created }}</td>
                                <td>{{ b.offer}}</td>
                                <td>{{ b.shares}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'app:confirm-bids' %}" style="margin-top: 1rem;" class="btn waves-light waves-effect pink">Confirm Bids</a>
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

              
{% load static %}

<section class="section">
    <section class="container">
        <section class="row">
            <div class="col l3 s12">
                <div class="card">
                    <div class="card-content center">
                        <p class="chip">Registered Users</p>
                        <h4 id="total_users"></h4>
                    </div>
                </div>
            </div>
            <div class="col l3 s12">
                <div class="card">
                        <div class="card-content center">
                                <p class="chip">Total Companies</p>
                                <h4 id="total_companies"></h4>
                            </div>
                </div>
            </div>
            <div class="col l3 s12">
                <div class="card">
                        <div class="card-content center">
                                <p class="chip">Total Offers ($)</p>
                                <h4><span id="total_offers"></span><span>K</span></h4>
                            </div>
                </div>
            </div>
            <div class="col l3 s12">
                    <div class="card">
                    <div class="card-content center">
                            <p class="chip">Total Placements</p>
                            <h4 id="total_placements"></h4>
                        </div>
                    </div>
                </div>
        </section>

        <section class="row">
            <div class="col l12 s12">
                <div class="card">
                    <div class="card-content center">
                            <h5>Top 5 placements by $</h5>
                            <canvas id="myChart"></canvas>
                    </div>
                </div>
            </div>
        </section>
    </section>
</section>

{% include 'footer.html' %}

<script>
// Number Incrementer function 
// from https://stackoverflow.com/questions/16994662/count-animation-from-number-a-to-b
function animateValue(id, start, end, duration) {
    var range = end - start;
    var current = start;
    var increment;
    var increment = end > start? 1 : -1;
    var stepTime = Math.abs(Math.floor(duration / range));
    var obj = document.getElementById(id);
    var timer = setInterval(function() {
        current += increment;
        obj.innerText = current;
        if (current == end) {
            clearInterval(timer);
        }
    }, stepTime);
}

animateValue("total_companies", 0, {{ total_companies }}, 1750);
animateValue("total_placements", 0, {{ total_placements }}, 1750);
animateValue("total_users", 0, {{ total_users }}, 1750);
animateValue("total_offers", 0, {{ total_offers }}, 500);
</script>
<script>
        // Chart.js code
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
                labels: {{ top_5_offer_names|safe }},
                datasets: [{
                    label: '# of offers',
                    data:{{ top_5_offer_values|safe }},
                    backgroundColor: 'rgba(48, 63, 159, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                legend: {
                    display: false
                },
                scales: {
                    yAxes: [{
                        gridLines: {display:false},
                        ticks: {
                            beginAtZero: true,
                            maxTicksLimit: 5
                        }
                    }],
                    xAxes: [{
                        gridLines: {display:true,  color:'#F5F5F5'},
                        ticks: {
                            beginAtZero: true,
                            maxTicksLimit: 6
                        }
                    }]
                }
            }
        });
        </script>

{% endblock content %}

templates/emailing.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %} {% load static %}

{% block body %}

<br>
<br>
<div class="container" align="center">
    <form action="/emailing" method="post">
      {% csrf_token %}
        <section class="vh-10 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">MAIL</h2>
              <p class="text-white-50 mb-5">Enter email to send using django</p>
              <div class="form-outline form-white mb-4">
                <input type="text" id="typeEmailX" name="email" class="form-control form-control-lg" placeholder="Enter your Email" />
                <input type="text" id="typeFeedbackX" name="feedback" class="form-control form-control-lg" placeholder="Feedback" />
              </div>
              <br>
              <br>
              <button class="b-tn btn-outline-light btn-lg px-5" type="submit">SUBMIT</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    </form>
</div>



{% endblock %}</body>
{% include 'footer.html' %} {% endblock content %}

templates/home.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %} {% load static %}

<section class="section">
    <section class="container">
        {% if user.is_authenticated == False %}
        <div class="card z-depth-2">
            <div class="card-content">
                <h3>BIDDING SYSTEM</h3>
                <img class="card-img-top" src="static/apple-icon.png" alt="Card image cap" height="260">
                <h5>Notice</h5>
                <p class="custom-font-1">You must have a registered account and be logged in, in order to view and place bids within our marketplace.</p>
            </div>
        </div>
        {% endif %}

        <div class="card z-depth-2">
            <div class="card-content">
                
                <h5>The Marketplace</h5>

                <p class="custom-font-1">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus ullam, odit iure incidunt inventore praesentium consectetur in animi rerum labore ab esse ex deleniti deserunt quaerat sapiente sunt quis a?</p>
                <a href="{% url 'app:placements' %}" class="btn waves-effect waves-light pink" style="margin-top: 1rem;">
                        <i class="material-icons left">store</i>visit marketplace</a>
                <img class="responsive-img fade-in" src="{% static 'austin-distel-1555609-unsplash.jpg' %}" alt="">
            </div>
        </div>


        <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    News (July)
                </h5>
                <p class="custom-font-1">Sunt excepteur do culpa velit consequat deserunt aute deserunt. Voluptate sit cillum cillum nostrud. Esse duis eu ut minim ad excepteur consequat amet est. Ullamco Lorem tempor excepteur veniam do ea incididunt anim eu non est eu voluptate
                    adipisicing.</p>
                <p class="custom-font-1"><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum culpa neque rerum sit maiores blanditiis et, dolorem labore, architecto harum explicabo optio nemo quo aut. Pariatur cum laboriosam id vel.</p>
                <p class="custom-font-1"><br>Velit et anim ea occaecat mollit enim commodo fugiat nisi anim fugiat. Fugiat ut occaecat consequat qui ex sunt proident esse aliquip adipisicing Lorem. Ullamco reprehenderit cupidatat ipsum non voluptate magna occaecat ullamco veniam
                    excepteur. Minim duis nostrud ex enim laboris minim irure dolore dolor aute occaecat dolor. Cillum do labore dolor consectetur fugiat enim voluptate. Sunt esse commodo laboris ut ipsum tempor nisi amet id anim aliqua aliquip fugiat.</p>
                <img class="responsive-img fade-in" src="{% static 'franck-v-628397-unsplash.jpg' %}" alt="">
            </div>
        </div>

        <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    News (June)
                </h5>
                <p class="custom-font-1">Sunt excepteur do culpa velit consequat deserunt aute deserunt. Voluptate sit cillum cillum nostrud. Esse duis eu ut minim ad excepteur consequat amet est. Ullamco Lorem tempor excepteur veniam do ea incididunt anim eu non est eu voluptate
                    adipisicing.</p>
                <p class="custom-font-1"><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum culpa neque rerum sit maiores blanditiis et, dolorem labore, architecto harum explicabo optio nemo quo aut. Pariatur cum laboriosam id vel.</p>
                <p class="custom-font-1"><br>Velit et anim ea occaecat mollit enim commodo fugiat nisi anim fugiat. Fugiat ut occaecat consequat qui ex sunt proident esse aliquip adipisicing Lorem. Ullamco reprehenderit cupidatat ipsum non voluptate magna occaecat ullamco veniam
                    excepteur. Minim duis nostrud ex enim laboris minim irure dolore dolor aute occaecat dolor. Cillum do labore dolor consectetur fugiat enim voluptate. Sunt esse commodo laboris ut ipsum tempor nisi amet id anim aliqua aliquip fugiat.</p>
                <img class="responsive-img fade-in" src="{% static 'priscilla-du-preez-623040-unsplash.jpg' %}" alt="">
            </div>
        </div>

        <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    News (May)
                </h5>
                <p class="custom-font-1">Sunt excepteur do culpa velit consequat deserunt aute deserunt. Voluptate sit cillum cillum nostrud. Esse duis eu ut minim ad excepteur consequat amet est. Ullamco Lorem tempor excepteur veniam do ea incididunt anim eu non est eu voluptate
                    adipisicing.</p>
                <p class="custom-font-1"><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum culpa neque rerum sit maiores blanditiis et, dolorem labore, architecto harum explicabo optio nemo quo aut. Pariatur cum laboriosam id vel.</p>
                <p class="custom-font-1"><br>Velit et anim ea occaecat mollit enim commodo fugiat nisi anim fugiat. Fugiat ut occaecat consequat qui ex sunt proident esse aliquip adipisicing Lorem. Ullamco reprehenderit cupidatat ipsum non voluptate magna occaecat ullamco veniam
                    excepteur. Minim duis nostrud ex enim laboris minim irure dolore dolor aute occaecat dolor. Cillum do labore dolor consectetur fugiat enim voluptate. Sunt esse commodo laboris ut ipsum tempor nisi amet id anim aliqua aliquip fugiat.</p>
                <img class="responsive-img fade-in" src="{% static 'lycs-architecture-744230-unsplash.jpg' %}" alt="">
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

templates/login.html
{% extends 'base.html' %} {% block content %}
<main>
    <h3 align="center"><mark>{{msg}}</mark></h3>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l8 m12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Login page</h5>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Username
                                    </label>
                                    <input type="text" name="username">
                                </div>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Password
                                    </label>
                                    <input type="password" name="password">
                                </div>
                                <div class="input-field">
                                    <button style="margin-top: 1rem;" class="btn waves-effect waves-light pink" type="submit">Login</button>
                                </div>
                                <p>Don't have an account? click <a href="{% url 'app:register' %}" style="margin-top: 1rem;" type="a">here</a> to register.</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

    </section>
</main>
{% include 'footer.html' %} {% endblock content %}

templates/nav.html
<nav>
<div class="nav-wrapper indigo darken-2">
    <div class="container">
    <!-- <a href="{% url 'app:home' %}" class="brand-logo" style="font-size: 1.3rem;">
       <strong>BIDDING PLATFORM</strong></a> -->
    <a href="#" data-target="mobile-demo" class="sidenav-trigger waves-effect waves-light"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
            <li><a href="{% url 'app:home' %}"><i class="material-icons">home</i></a></li>
        <li><a href="{% url 'app:placements' %}"><i class="material-icons">store</i></a></li>
        <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons">view_list</i></a></li>
        <li><a href="{% url 'app:about' %}"><i class="material-icons">help</i></a></li>
        <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i></a></li>
        
    </ul>

    <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
        <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:addmin' %}">Admin/Seller</a></li>
        <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:emailing' %}">Feedback</a></li>
            <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
            <li>Logged in as <strong>{{ user.username }}</strong></li>
        {% else %}
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:addmin' %}">
                Admin
            </a>
            </li>
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:register' %}">
                Register
            </a>
            </li>
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:login' %}">
                Login
            </a>
        </li>

        {% endif %}
    </ul>
</div>
</div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'app:home' %}"><i class="material-icons">home</i>Home</a></li>
    <li><a href="{% url 'app:placements' %}"><i class="material-icons">store</i>Marketplace</a></li>
    <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons">view_list</i>My Bids</a></li>
    <li><a href="{% url 'app:about' %}"><i class="material-icons">assignment</i>About</a></li>
    <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i>Analytics</a></li>
    {% if user.is_authenticated %}
        <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
    {% else %}
    <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:register' %}">
        Register</a>
    </li>
    <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:login' %}">
        Login</a>
    </li>
    {% endif %}
</ul>

templates/placements.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

              
{% load static %}

<section class="section">
    <section class="container">
        
            <div class="col s12">
                    <div class="card">
                            <div class="card-content">
                                <h4>Welcome to the marketplace</h4>
                                <p>Explore placements by various listed companies</p>
                                <img src="{% static 'ishant-mishra-1349434-unsplash.jpg' %}" alt="" class="responsive-img fade-in">
                            </div>
                        </div>
            </div>

            <div class="card">
                <div class="card-content">
                        <table class="table responsive-table">
                                <thead>
                                    <tr>
                              
                                        <th>Placement Desc</th>
                                        <th>Company</th>
                                        <th>Added</th>
                                        <th>Modified</th>
                                        <th>View Details</th>
                                    </tr>
                                </thead>
                
                                <tbody>
                                        {%for p in placements %}
                                        <tr>
                             
                                            <td>{{ p.placement_title }}</td>
                                            <td><span class="chip indigo white-text">{{ p.placement_company }}</span></td>
                                            <td>{{ p.placement_created }}</td>
                                            <td>{{ p.placement_modified }}</td>
                                            <td><a href="{% url 'app:placement-detail' p.placement_slug %}" style="margin-top: 1rem;" class="btn pink waves-effect waves-light">View Details</a></td>
                                        </tr>
                                        {% endfor %}
                                </tbody>
                            </table>

                            <ul class="pagination center">
                                {% if placements.has_previous %}
                                <li class="waves-effect"><a href="?page={{placements.previous_page_number}}">{{ placements.previous_page_number}}</a></li>
                                {% endif %}

                                <li class="active indigo"><a href="#!">{{placements.number}}</a></li>
                               
                                {% if placements.has_next %}
                                <li class="waves-effect"><a href="?page={{placements.next_page_number}}">{{ placements.next_page_number}}</a></li>
                                {% endif %}
                            </ul>
                                            
                </div>
            </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/register.html
{% extends 'base.html' %} {% block content %}
<main>
    <h3 align="center"><mark>{{msg}}</mark></h3>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l12 s12">
                    <div class="card">
                        <div class="card-content">

                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Registration page</h5>
                                {{ form.as_p }}
                                <div class="center">
                                    <button style="margin-top: 1rem;" class="btn pink waves-effect waves-light" type="submit">Create Account</button>
                                </div>
                                <a href="{% url 'app:home' %}" style="margin-top: 1rem;">Go back to home page.</a>

                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</main>
{% include 'footer.html' %} {% endblock content %}